### ISSUE TITLE
書き込み権限がない

### ISSUE THREAD

**Issue by Kobayashi123** [ShoNakatani/test_pull#1]
```bash
git push
　ERROR: Permission to ShoNakatani/test_pull.git denied to Kobayashi123.
　fatal: Could not read from remote repository.

　Please make sure you have the correct access rights and the repository exists.
```

コラボレータに追加してくださいな
[Github docs Error: Permission to user/repo denied to other-user](https://docs.github.com/ja/authentication/troubleshooting-ssh/error-permission-to-userrepo-denied-to-other-user)

↓ 多分これ
[コラボレーターを個人リポジトリに招待する](https://docs.github.com/ja/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

アカウントは、`[Kobayashi123](https://github.com/Kobayashi123)`

**Comment by ShoNakatani** [comment]
多分いけると思う

**Comment by Kobayashi123** [comment]
アクセスできるようになった。
